export const TOGGLE_POPUP = 'TOGGLE_POPUP';
export const CREATE_LISTING = 'CREATE_LISTING';
export const UPDATE_SELECTED_BRAND = 'UPDATE_SELECTED_BRAND';
export const UPDATE_SELECTED_CONDITION = 'UPDATE_SELECTED_CONDITION';
export const UPDATE_SELECTED_SIZE = 'UPDATED_SELECTED_SIZE';
export const UPDATE_PRICE = 'UPDATED_PRICE';
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const HANDLE_UPLOAD_IMAGE = 'HANDLE_UPLOAD_IMAGE';
export const GET_FILTERS = 'GET_FILTERS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const TOGGLE_DETAIL = 'TOGGLE_DETAIL';
export const DISPLAY_LISTING = 'DISPLAY_LISTING';
export const HANDLE_SUBMIT = 'HANDLE_SUBMIT';
export const ADD_WISHLIST = 'ADD_WISHLIST';
export const DEL_WISHLIST = 'DEL_WISHLIST';
export const APPLY_FILTER = 'APPLY_FILTERS';


